main:
  - name: Journey
    pageRef: /journey
    weight: 10
    params:
      icon: chart
  - name: Posts
    pageRef: /posts
    weight: 20
    params:
      icon: posts
  - name: Projects
    pageRef: /projects
    weight: 30
    params:
      icon: projects

  - name: More
    weight: 40
    params:
      icon: layers

  - name: Categories
    pageRef: /categories
    weight: 1
    parent: More
    params:
      icon: categories
  - name: Tags
    pageRef: /tags
    weight: 2
    parent: More
    params:
      icon: tags
  # - name: Archives
  #   pageRef: /archives
  #   weight: 3
  #   parent: More
  #   params:
  #     icon: archive

## footer menu
# footer:
#   - name: Timeline
#     pageRef: /timeline
#     weight: 10
#     params:
#       icon: chart
#   - name: About
#     pageRef: /about
#     weight: 20
#     params:
#       icon: about
#   - name: RSS Feed
#     url: /index.xml
#     weight: 30
#     params:
#       icon: rss

### footer social link
social:
 - name: Blog GitHub
   url: https://github.com/ilkersigirci/my-blog
   weight: 10
   params:
     icon: github
 - name: Blog RSS Feed
   url: /index.xml
   weight: 10
   params:
     icon: rss
