version: '3.9'
name: my-blog

networks:
  bun_network:
    driver: bridge

services:
  my-blog:
    container_name: my-blog
    # The name of the image that will be created when building this container
    image: my-blog:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - bun_network
    ports:
      - 3010:3000
